#!/bin/bash -ue

git-ignorefiles(){
  for _f; do
    local f="$_f"
    local gitignore="$(dirname "$f")"/.gitignore
    local b="$(basename "$f")"
    echo "$b" >>"$gitignore"
    $EDITOR "$gitignore"
    git add "$gitignore"
    git ci -m "$(dirname "$f")/.gitignore: +$b" -- "$gitignore"
  done
}

git-ignorefiles "$@"
